# Required to run your project under the correct environment.
language: php

env:
  - PACKAGE_VERSION="3.0.0"
  - CODECOV_TOKEN="0e696754-7bc4-45b8-915f-c4f1f9a12685"

# Versions of PHP you want your project run with.
php:
  - 7.2
  - 7.3

# Commands to be run before your environment runs.
before_script:
- "composer install"

script:
- vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)

# Customize when the notification emails are sent.
notifications:
 email: lablnet01@gmail.com
